# Generated by Django 5.0.6 on 2024-05-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.TextField()),
                ("data", models.TextField()),
            ],
        ),
    ]
