# Generated by Django 5.0.6 on 2024-05-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="fileData",
        ),
        migrations.RenameField(
            model_name="filedata",
            old_name="file",
            new_name="fileName",
        ),
    ]
