# Generated by Django 5.0.6 on 2024-05-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0002_rename_user_filedata_rename_file_filedata_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="filedata",
            name="fileLink",
            field=models.TextField(null=True),
        ),
    ]
